server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~ ^/api/(.*)$ {
        proxy_pass https://buzzhive-test.onrender.com/api/$1;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
    }

    location ~ ^/uploads/(.*)$ {
        proxy_pass https://buzzhive-test.onrender.com/uploads/$1;
        proxy_http_version 1.1;
    }
}