/**
 * UI tests for Admin features.
 * Generated by splitting buzzhive.spec.ts.
 */

 // runs only locally
import { test, expect } from '../fixtures';

test.describe('Buzzhive Social Network - Admin', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/');
  });

  test.afterEach(async ({ page }, testInfo) => {
    if (testInfo.status !== testInfo.expectedStatus) {
      await page.screenshot({ path: testInfo.outputPath(`${testInfo.title}.png`), fullPage: true });
    }
  });
  
  test('admin dashboard shows stats', async ({ page }) => {
    await page.goto('/login');
    await page.fill('[data-testid="auth-email-input"]', 'admin@buzzhive.com');
    await page.fill('[data-testid="auth-password-input"]', 'admin123');
    await page.click('[data-testid="auth-login-btn"]');
    await page.waitForURL('**/');
    
    await page.click('[data-testid="nav-admin"]');
    await page.waitForURL('**/admin**');
    await page.waitForLoadState('networkidle');
    
    await expect(page.locator('[data-testid="admin-stats-users-count"]')).toBeVisible({ timeout: 5000 });
    await expect(page.locator('[data-testid="admin-stats-posts-count"]')).toBeVisible({ timeout: 5000 });
    
    console.log('✅ Admin dashboard loaded!');
  });
  
  test('regular user cannot access admin', async ({ page }) => {
    await page.goto('/login');
    await page.fill('[data-testid="auth-email-input"]', 'alice@buzzhive.com');
    await page.fill('[data-testid="auth-password-input"]', 'alice123');
    await page.click('[data-testid="auth-login-btn"]');
    await page.waitForURL('**/');
    
    const adminLink = page.locator('[data-testid="nav-admin"]');
    await expect(adminLink).not.toBeVisible({ timeout: 2000 });
    
    console.log('✅ Admin link hidden for regular user!');
  });
  
  test('admin can ban a user', async ({ page }) => {
    await page.goto('/login');
    await page.fill('[data-testid="auth-email-input"]', 'admin@buzzhive.com');
    await page.fill('[data-testid="auth-password-input"]', 'admin123');
    await page.click('[data-testid="auth-login-btn"]');
    await page.waitForURL('**/');
    
    await page.goto('/admin/users');
    await page.waitForLoadState('networkidle');
    
    const banBtn = page.locator('[data-testid^="admin-ban-btn-"]').first();
    await banBtn.waitFor({ state: 'visible', timeout: 5000 });
    await banBtn.click();
    
    await expect(page.locator('[data-testid^="admin-ban-btn-"]').first()).toBeVisible();
    
    console.log('✅ User banned successfully!');
  });
  
  test('banned user cannot login', async ({ page }) => {
    await page.goto('/login');
    await page.fill('[data-testid="auth-email-input"]', 'frank@buzzhive.com');
    await page.fill('[data-testid="auth-password-input"]', 'frank123');
    await page.click('[data-testid="auth-login-btn"]');
    
    await expect(page.locator('[data-testid="auth-error-message"]')).toBeVisible();
    
    console.log('✅ Banned user login blocked!');
  });
  
  test('admin can change user role', async ({ page }) => {
    await page.goto('/login');
    await page.fill('[data-testid="auth-email-input"]', 'admin@buzzhive.com');
    await page.fill('[data-testid="auth-password-input"]', 'admin123');
    await page.click('[data-testid="auth-login-btn"]');
    await page.waitForURL('**/');
    
    await page.goto('/admin/users');
    await page.waitForLoadState('networkidle');
    
    const roleSelect = page.locator('[data-testid^="admin-role-select-"]').first();
    await roleSelect.waitFor({ state: 'visible', timeout: 5000 });
    
    console.log('✅ Role selector visible!');
  });
});
