/**
 * UI tests for Comments.
 * Generated by splitting buzzhive.spec.ts.
 */

 // runs only locally
import { test, expect } from '../fixtures';

test.describe('Buzzhive Social Network - Comments', () => {
  test.beforeEach(async ({ page, loginPage }) => {
    await page.goto('/');
  });

  test.afterEach(async ({ page }, testInfo) => {
    if (testInfo.status !== testInfo.expectedStatus) {
      await page.screenshot({ path: testInfo.outputPath(`${testInfo.title}.png`), fullPage: true });
    }
  });
  
  test('can add a comment to post', async ({ page, loginPage }) => {
    await loginPage.goto('/login');
    await loginPage.login('alice@buzzhive.com', 'alice123');
    await page.waitForURL('**/');
    
    const commentBtn = page.locator('[data-testid^="post-comment-btn-"]').first();
    await commentBtn.click();
    await page.waitForLoadState('networkidle');
    
    const commentInput = page.locator('[data-testid="comment-input"]');
    await commentInput.waitFor({ state: 'visible', timeout: 5000 });
    
    await commentInput.fill('Great post!');
    await page.click('[data-testid="comment-submit-btn"]');
    
    await expect(page.locator('text=Great post!')).toBeVisible();
    
    console.log('✅ Comment added!');
  });
});
