/**
 * UI tests for Follows.
 * Generated by splitting buzzhive.spec.ts.
 */

 // runs only locally
import { test, expect } from '../fixtures';

test.describe('Buzzhive Social Network - Follows', () => {
  test.beforeEach(async ({ page, loginPage }) => {
    await page.goto('/');
  });

  test.afterEach(async ({ page }, testInfo) => {
    if (testInfo.status !== testInfo.expectedStatus) {
      await page.screenshot({ path: testInfo.outputPath(`${testInfo.title}.png`), fullPage: true });
    }
  });
  
  test('can follow and unfollow a user', async ({ page, loginPage }) => {
    await loginPage.goto('/login');
    await loginPage.login('alice@buzzhive.com', 'alice123');
    await page.waitForURL('**/');
    
    await page.goto('/profile/bob_photo');
    await page.waitForLoadState('networkidle');
    
    const followBtn = page.locator('[data-testid="profile-follow-btn"]');
    await followBtn.waitFor({ state: 'visible', timeout: 10000 });
    
    await followBtn.click();
    await expect(followBtn).toBeVisible();
    console.log('✅ Follow clicked!');
    
    await followBtn.click();
    await expect(followBtn).toBeVisible();
    console.log('✅ Unfollow clicked!');
  });
});
