/**
 * UI tests for Logout.
 * Generated by splitting buzzhive.spec.ts.
 */

 // runs only locally
import { test, expect } from '../fixtures';

test.describe('Buzzhive Social Network - Logout', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/');
  });

  test.afterEach(async ({ page }, testInfo) => {
    if (testInfo.status !== testInfo.expectedStatus) {
      await page.screenshot({ path: testInfo.outputPath(`${testInfo.title}.png`), fullPage: true });
    }
  });
  
  test('can logout successfully', async ({ page }) => {
    await page.goto('/login');
    await page.fill('[data-testid="auth-email-input"]', 'alice@buzzhive.com');
    await page.fill('[data-testid="auth-password-input"]', 'alice123');
    await page.click('[data-testid="auth-login-btn"]');
    await page.waitForURL('**/');
    
    const logoutBtn = page.locator('[data-testid="auth-logout-btn"]');
    await logoutBtn.click();
    await page.waitForLoadState('networkidle');
    
    await expect(page.locator('[data-testid="auth-login-btn"]')).toBeVisible({ timeout: 5000 });
    console.log('✅ Logout successful!');
  });
});
