/**
 * UI tests for Messages.
 * Generated by splitting buzzhive.spec.ts.
 */

 // runs only locally
import { test, expect } from '../fixtures';

test.describe('Buzzhive Social Network - Messages', () => {
  test.beforeEach(async ({ page, loginPage }) => {
    await page.goto('/');
  });

  test.afterEach(async ({ page }, testInfo) => {
    if (testInfo.status !== testInfo.expectedStatus) {
      await page.screenshot({ path: testInfo.outputPath(`${testInfo.title}.png`), fullPage: true });
    }
  });
  
  test('messages page accessible', async ({ page, loginPage }) => {
    await loginPage.goto('/login');
    await loginPage.login('alice@buzzhive.com', 'alice123');
    await page.waitForURL('**/');
    await page.click('[data-testid="nav-messages"]');
    await page.waitForURL('**/messages**');
    
    await expect(page.locator('[data-testid="new-conversation-btn"]')).toBeVisible({ timeout: 5000 });
    console.log('✅ Messages page accessible!');
  });
});
