/**
 * UI tests for Moderator features.
 * Generated by splitting buzzhive.spec.ts.
 */

 // runs only locally
import { test, expect } from '../fixtures';

test.describe('Buzzhive Social Network - Moderator', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/');
  });

  test.afterEach(async ({ page }, testInfo) => {
    if (testInfo.status !== testInfo.expectedStatus) {
      await page.screenshot({ path: testInfo.outputPath(`${testInfo.title}.png`), fullPage: true });
    }
  });
  
  test('moderator can access admin panel', async ({ page }) => {
    await page.goto('/login');
    await page.fill('[data-testid="auth-email-input"]', 'mod@buzzhive.com');
    await page.fill('[data-testid="auth-password-input"]', 'mod123');
    await page.click('[data-testid="auth-login-btn"]');
    await page.waitForURL('**/');
    
    const adminLink = page.locator('[data-testid="nav-admin"]');
    await expect(adminLink).toBeVisible({ timeout: 5000 });
    
    await adminLink.click();
    await page.waitForURL('**/admin**');
    console.log('✅ Moderator can access admin panel!');
  });
  
  test('moderator can delete any post', async ({ page }) => {
    await page.goto('/login');
    await page.fill('[data-testid="auth-email-input"]', 'mod@buzzhive.com');
    await page.fill('[data-testid="auth-password-input"]', 'mod123');
    await page.click('[data-testid="auth-login-btn"]');
    await page.waitForURL('**/');
    
    const menuBtn = page.locator('[data-testid^="post-menu-btn-"]').first();
    await menuBtn.waitFor({ state: 'visible', timeout: 5000 });
    await menuBtn.click();
    await expect(page.locator('[data-testid^="post-delete-btn-"]').first()).toBeVisible();
    
    const deleteBtn = page.locator('[data-testid^="post-delete-btn-"]').first();
    if (await deleteBtn.isVisible()) {
      await deleteBtn.click();
      await expect(page.locator('[data-testid^="post-menu-btn-"]').first()).toBeVisible();
      console.log('✅ Moderator can delete posts!');
    } else {
      console.log('ℹ️ No delete option visible');
    }
  });
  
  test('moderator cannot ban users', async ({ page }) => {
    await page.goto('/login');
    await page.fill('[data-testid="auth-email-input"]', 'mod@buzzhive.com');
    await page.fill('[data-testid="auth-password-input"]', 'mod123');
    await page.click('[data-testid="auth-login-btn"]');
    await page.waitForURL('**/');
    
    await page.goto('/admin/users');
    
    const banBtn = page.locator('[data-testid^="admin-ban-btn-"]').first();
    await expect(banBtn).not.toBeVisible({ timeout: 3000 });
    
    console.log('✅ Moderator cannot ban users!');
  });
});
