/**
 * UI tests for Navigation.
 * Generated by splitting buzzhive.spec.ts.
 */

 // runs only locally
import { test, expect } from '../fixtures';

test.describe('Buzzhive Social Network - Navigation', () => {
  test.beforeEach(async ({ page, loginPage }) => {
    await page.goto('/');
  });

  test.afterEach(async ({ page }, testInfo) => {
    if (testInfo.status !== testInfo.expectedStatus) {
      await page.screenshot({ path: testInfo.outputPath(`${testInfo.title}.png`), fullPage: true });
    }
  });
  
  test.use({ storageState: { cookies: [], origins: [] } });
  
  test('navigation elements visible after login', async ({ page, loginPage }) => {
    await loginPage.goto('/login');
    await loginPage.login('alice@buzzhive.com', 'alice123');
    await page.waitForURL('**/');
    
    await expect(page.locator('[data-testid="nav-feed"]')).toBeVisible({ timeout: 5000 });
    await expect(page.locator('[data-testid="nav-explore"]')).toBeVisible({ timeout: 5000 });
    await expect(page.locator('[data-testid="nav-messages"]')).toBeVisible({ timeout: 5000 });
    await expect(page.locator('[data-testid="nav-notifications"]')).toBeVisible({ timeout: 5000 });
    await expect(page.locator('[data-testid="nav-profile"]')).toBeVisible({ timeout: 5000 });
    console.log('✅ Navigation elements visible!');
  });
  
  test('can navigate to profile', async ({ page, loginPage }) => {
    await loginPage.goto('/login');
    await loginPage.login('alice@buzzhive.com', 'alice123');
    await page.waitForLoadState('networkidle');
    await page.click('[data-testid="nav-profile"]');
    await page.waitForLoadState('networkidle');
    await expect(page.locator('[data-testid="profile-avatar"]')).toBeVisible({ timeout: 5000 });
    console.log('✅ Profile page accessible!');
  });

  test('can navigate to search', async ({ page, loginPage }) => {
    await loginPage.goto('/login');
    await loginPage.login('alice@buzzhive.com', 'alice123');
    await page.waitForURL('**/');
    await page.click('[data-testid="nav-search"]');
    await page.waitForURL('**/search**');
    console.log('✅ Search page accessible!');
  });

  test('can navigate to explore', async ({ page, loginPage }) => {
    await loginPage.goto('/login');
    await loginPage.login('alice@buzzhive.com', 'alice123');
    await page.waitForURL('**/');
    await page.click('[data-testid="nav-explore"]');
    await page.waitForURL('**/explore**');
    console.log('✅ Explore page accessible!');
  });
});
