/**
 * UI tests for Notifications.
 * Generated by splitting buzzhive.spec.ts.
 */

 // runs only locally
import { test, expect } from '../fixtures';

test.describe('Buzzhive Social Network - Notifications', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/');
  });

  test.afterEach(async ({ page }, testInfo) => {
    if (testInfo.status !== testInfo.expectedStatus) {
      await page.screenshot({ path: testInfo.outputPath(`${testInfo.title}.png`), fullPage: true });
    }
  });
  
  test('notifications page accessible', async ({ page }) => {
    await page.goto('/login');
    await page.fill('[data-testid="auth-email-input"]', 'alice@buzzhive.com');
    await page.fill('[data-testid="auth-password-input"]', 'alice123');
    await page.click('[data-testid="auth-login-btn"]');
    await page.waitForURL('**/');
    await page.click('[data-testid="nav-notifications"]');
    await page.waitForURL('**/notifications**');
    
    await expect(page.locator('[data-testid="notifications-mark-all-btn"]')).toBeVisible({ timeout: 5000 });
    await expect(page.locator('[data-testid="notifications-filter-all"]')).toBeVisible({ timeout: 5000 });
    console.log('✅ Notifications page accessible!');
  });
  
  test('can mark all notifications as read', async ({ page }) => {
    await page.goto('/login');
    await page.fill('[data-testid="auth-email-input"]', 'alice@buzzhive.com');
    await page.fill('[data-testid="auth-password-input"]', 'alice123');
    await page.click('[data-testid="auth-login-btn"]');
    await page.waitForURL('**/');
    await page.click('[data-testid="nav-notifications"]');
    await page.waitForLoadState('networkidle');
    
    const markAllBtn = page.locator('[data-testid="notifications-mark-all-btn"]');
    if (await markAllBtn.isVisible()) {
      await markAllBtn.click();
      await expect(page.locator('[data-testid="nav-notifications"]')).toBeVisible();
      console.log('✅ Mark all as read clicked!');
    } else {
      console.log('ℹ️ No unread notifications to mark');
    }
  });
});
