/**
 * UI tests for Posts (feed, create, like, bookmark).
 * Generated by splitting buzzhive.spec.ts.
 */

 // runs only locally
import { test, expect } from '../fixtures';

test.describe('Buzzhive Social Network - Posts', () => {
  test.beforeEach(async ({ page, loginPage }) => {
    await page.goto('/');
  });

  test.afterEach(async ({ page }, testInfo) => {
    if (testInfo.status !== testInfo.expectedStatus) {
      await page.screenshot({ path: testInfo.outputPath(`${testInfo.title}.png`), fullPage: true });
    }
  });
  
  test('feed shows posts', async ({ page, loginPage }) => {
    await loginPage.goto('/login');
    await loginPage.login('alice@buzzhive.com', 'alice123');
    await page.waitForURL('**/');
    
    await expect(page.locator('[data-testid="post-composer-input"]')).toBeVisible({ timeout: 5000 });
    console.log('✅ Feed page accessible!');
  });
  
  test('can create a post', async ({ page, loginPage }) => {
    await loginPage.goto('/login');
    await loginPage.login('alice@buzzhive.com', 'alice123');
    await page.waitForURL('**/');
    
    const testContent = `Hello from Playwright! ${Date.now()}`;
    await page.fill('[data-testid="post-composer-input"]', testContent);
    
    await Promise.all([
      page.waitForResponse(res => res.url().includes('/api/posts') && res.status() === 201),
      page.click('[data-testid="post-composer-submit"]'),
    ]);
    
    await expect(page.locator(`text=${testContent}`)).toBeVisible({ timeout: 5000 });
    console.log('✅ Post created successfully!');
  });

  test('can like and unlike a post', async ({ page, loginPage }) => {
    await loginPage.goto('/login');
    await loginPage.login('alice@buzzhive.com', 'alice123');
    await page.waitForURL('**/');
    
    const likeBtn = page.locator('[data-testid^="post-like-btn-"]').first();
    await likeBtn.waitFor({ state: 'visible', timeout: 5000 });
    
    const initialCount = await page.locator('[data-testid^="post-likes-count-"]').first().textContent();
    
    await likeBtn.click();
    await expect(page.locator('[data-testid^="post-likes-count-"]').first()).toBeVisible();
    
    const newCount = await page.locator('[data-testid^="post-likes-count-"]').first().textContent();
    console.log(`Likes: ${initialCount} → ${newCount}`);
    
    await likeBtn.click();
    await expect(page.locator('[data-testid^="post-likes-count-"]').first()).toBeVisible();
    console.log('✅ Like/Unlike works!');
  });
  
  test('can bookmark a post', async ({ page, loginPage }) => {
    await loginPage.goto('/login');
    await loginPage.login('alice@buzzhive.com', 'alice123');
    await page.waitForURL('**/');
    
    const bookmarkBtn = page.locator('[data-testid^="post-bookmark-btn-"]').first();
    await bookmarkBtn.waitFor({ state: 'visible', timeout: 5000 });
    
    await bookmarkBtn.click();
    await expect(bookmarkBtn).toBeVisible();
    
    console.log('✅ Bookmark toggled!');
  });
});
