/**
 * UI tests for Profile.
 * Generated by splitting buzzhive.spec.ts.
 */

 // runs only locally
import { test, expect } from '../fixtures';

test.describe('Buzzhive Social Network - Profile', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/');
  });

  test.afterEach(async ({ page }, testInfo) => {
    if (testInfo.status !== testInfo.expectedStatus) {
      await page.screenshot({ path: testInfo.outputPath(`${testInfo.title}.png`), fullPage: true });
    }
  });
  
  test('profile page shows user info', async ({ page }) => {
    await page.goto('/login');
    await page.fill('[data-testid="auth-email-input"]', 'alice@buzzhive.com');
    await page.fill('[data-testid="auth-password-input"]', 'alice123');
    await page.click('[data-testid="auth-login-btn"]');
    await page.waitForURL('**/');
    await page.click('[data-testid="nav-profile"]');
    await page.waitForURL('**/profile**');
    
    await expect(page.locator('[data-testid="profile-display-name"]')).toBeVisible({ timeout: 5000 });
    await expect(page.locator('[data-testid="profile-username"]')).toBeVisible({ timeout: 5000 });
    await expect(page.locator('[data-testid="profile-followers-count"]')).toBeVisible({ timeout: 5000 });
    await expect(page.locator('[data-testid="profile-posts-count"]')).toBeVisible({ timeout: 5000 });
    console.log('✅ Profile info visible!');
  });

  test('can navigate to profile settings', async ({ page }) => {
    await page.goto('/login');
    await page.fill('[data-testid="auth-email-input"]', 'alice@buzzhive.com');
    await page.fill('[data-testid="auth-password-input"]', 'alice123');
    await page.click('[data-testid="auth-login-btn"]');
    await page.waitForURL('**/');
    await page.click('[data-testid="nav-profile"]');
    await page.waitForLoadState('networkidle');
    
    const editBtn = page.locator('[data-testid="profile-edit-btn"]');
    await editBtn.waitFor({ state: 'visible', timeout: 5000 });
    await editBtn.click();
    await page.waitForURL('**/settings**');
    
    await expect(page.locator('[data-testid="lang-en"]').first()).toBeVisible({ timeout: 5000 });
    console.log('✅ Profile edit page opened!');
  });
});
