/**
 * UI tests for Search.
 * Generated by splitting buzzhive.spec.ts.
 */

 // runs only locally
import { test, expect } from '../fixtures';

test.describe('Buzzhive Social Network - Search', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/');
  });

  test.afterEach(async ({ page }, testInfo) => {
    if (testInfo.status !== testInfo.expectedStatus) {
      await page.screenshot({ path: testInfo.outputPath(`${testInfo.title}.png`), fullPage: true });
    }
  });

  test('search page loads with all elements', async ({ page }) => {
    await page.goto('/login');
    await page.fill('[data-testid="auth-email-input"]', 'alice@buzzhive.com');
    await page.fill('[data-testid="auth-password-input"]', 'alice123');
    await page.click('[data-testid="auth-login-btn"]');
    await page.waitForURL('**/');

    await page.goto('/search');
    await page.waitForLoadState('networkidle');

    await expect(page.locator('[data-testid="nav-search-input"]')).toBeVisible({ timeout: 5000 });
    await expect(page.locator('button:has-text("Search")')).toBeVisible({ timeout: 5000 });
    console.log('✅ Search page loaded!');
  });

  test('can search for users', async ({ page }) => {
    await page.goto('/login');
    await page.fill('[data-testid="auth-email-input"]', 'alice@buzzhive.com');
    await page.fill('[data-testid="auth-password-input"]', 'alice123');
    await page.click('[data-testid="auth-login-btn"]');
    await page.waitForURL('**/');

    await page.goto('/search');
    await page.waitForLoadState('networkidle');

    const searchInput = page.locator('[data-testid="nav-search-input"]');
    await searchInput.fill('bob');

    const searchBtn = page.locator('button:has-text("Search")');
    await searchBtn.click();

    const usersTab = page.locator('button:has-text("users")');
    await expect(usersTab).toBeVisible({ timeout: 5000 });
    console.log('✅ User search executed!');
  });

  test('can search for posts', async ({ page }) => {
    await page.goto('/login');
    await page.fill('[data-testid="auth-email-input"]', 'alice@buzzhive.com');
    await page.fill('[data-testid="auth-password-input"]', 'alice123');
    await page.click('[data-testid="auth-login-btn"]');
    await page.waitForURL('**/');

    await page.goto('/search');
    await page.waitForLoadState('networkidle');

    const searchInput = page.locator('[data-testid="nav-search-input"]');
    await searchInput.fill('hello');

    const searchBtn = page.locator('button:has-text("Search")');
    await searchBtn.click();

    const postsTab = page.locator('button:has-text("posts")');
    await expect(postsTab).toBeVisible();
    await postsTab.click();

    console.log('✅ Post search executed and tab switched!');
  });

  test('can search for hashtags', async ({ page }) => {
    await page.goto('/login');
    await page.fill('[data-testid="auth-email-input"]', 'alice@buzzhive.com');
    await page.fill('[data-testid="auth-password-input"]', 'alice123');
    await page.click('[data-testid="auth-login-btn"]');
    await page.waitForURL('**/');

    await page.goto('/search');
    await page.waitForLoadState('networkidle');

    const searchInput = page.locator('[data-testid="nav-search-input"]');
    await searchInput.fill('tech');

    const searchBtn = page.locator('button:has-text("Search")');
    await searchBtn.click();

    const hashtagsTab = page.locator('button:has-text("hashtags")');
    await expect(hashtagsTab).toBeVisible();
    await hashtagsTab.click();

    console.log('✅ Hashtag search executed and tab switched!');
  });

  test('search by pressing Enter key', async ({ page }) => {
    await page.goto('/login');
    await page.fill('[data-testid="auth-email-input"]', 'alice@buzzhive.com');
    await page.fill('[data-testid="auth-password-input"]', 'alice123');
    await page.click('[data-testid="auth-login-btn"]');
    await page.waitForURL('**/');

    await page.goto('/search');
    await page.waitForLoadState('networkidle');

    const searchInput = page.locator('[data-testid="nav-search-input"]');
    await searchInput.fill('test');
    await searchInput.press('Enter');

    await expect(page.locator('[data-testid="nav-search-input"]')).toBeVisible();

    console.log('✅ Search triggered via Enter key!');
  });

  test('display correct result counts in tabs', async ({ page }) => {
    await page.goto('/login');
    await page.fill('[data-testid="auth-email-input"]', 'alice@buzzhive.com');
    await page.fill('[data-testid="auth-password-input"]', 'alice123');
    await page.click('[data-testid="auth-login-btn"]');
    await page.waitForURL('**/');

    await page.goto('/search');
    await page.waitForLoadState('networkidle');

    const searchInput = page.locator('[data-testid="nav-search-input"]');
    await searchInput.fill('alice');

    const searchBtn = page.locator('button:has-text("Search")');
    await searchBtn.click();

    const tabsWithCounts = page.locator('button:has-text("(")');
    await expect(tabsWithCounts.first()).toBeVisible();
    const count = await tabsWithCounts.count();
    console.log(`Found ${count} tabs with counts`);

    console.log('✅ Tab counts displayed correctly!');
  });

  test('empty search shows no results message', async ({ page }) => {
    await page.goto('/login');
    await page.fill('[data-testid="auth-email-input"]', 'alice@buzzhive.com');
    await page.fill('[data-testid="auth-password-input"]', 'alice123');
    await page.click('[data-testid="auth-login-btn"]');
    await page.waitForURL('**/');

    await page.goto('/search');
    await page.waitForLoadState('networkidle');

    const searchInput = page.locator('[data-testid="nav-search-input"]');
    await searchInput.fill('zzzzxyzzzz_nonexistent_query');

    const searchBtn = page.locator('button:has-text("Search")');
    await searchBtn.click();

    const noResultsMsg = page.locator('text=No users found');
    if (await noResultsMsg.isVisible({ timeout: 2000 }).catch(() => false)) {
      console.log('✅ No results message displayed!');
    } else {
      console.log('ℹ️ Results found or no message displayed');
    }
  });

  test('can switch between search result tabs', async ({ page }) => {
    await page.goto('/login');
    await page.fill('[data-testid="auth-email-input"]', 'alice@buzzhive.com');
    await page.fill('[data-testid="auth-password-input"]', 'alice123');
    await page.click('[data-testid="auth-login-btn"]');
    await page.waitForURL('**/');

    await page.goto('/search');
    await page.waitForLoadState('networkidle');

    const searchInput = page.locator('[data-testid="nav-search-input"]');
    await searchInput.fill('buzz');

    const searchBtn = page.locator('button:has-text("Search")');
    await searchBtn.click();

    const usersTab = page.locator('button:has-text("users")');
    const postsTab = page.locator('button:has-text("posts")');
    const hashtagsTab = page.locator('button:has-text("hashtags")');

    await usersTab.click();
    await expect(usersTab).toBeVisible();
    await postsTab.click();
    await expect(postsTab).toBeVisible();
    await hashtagsTab.click();
    await expect(hashtagsTab).toBeVisible();

    console.log('✅ Tab switching works!');
  });

  test('clicking search result user navigates to profile', async ({ page }) => {
    await page.goto('/login');
    await page.fill('[data-testid="auth-email-input"]', 'alice@buzzhive.com');
    await page.fill('[data-testid="auth-password-input"]', 'alice123');
    await page.click('[data-testid="auth-login-btn"]');
    await page.waitForURL('**/');

    await page.goto('/search');
    await page.waitForLoadState('networkidle');

    const searchInput = page.locator('[data-testid="nav-search-input"]');
    await searchInput.fill('bob');

    const searchBtn = page.locator('button:has-text("Search")');
    await searchBtn.click();

    const firstUserResult = page.locator('a[href*="/profile/"]').first();
    if (await firstUserResult.isVisible({ timeout: 2000 }).catch(() => false)) {
      await firstUserResult.click();
      await page.waitForLoadState('networkidle');
      expect(page.url()).toContain('/profile/');
      console.log('✅ User result navigation works!');
    } else {
      console.log('ℹ️ No user results found to click');
    }
  });

  test('search from navigation menu', async ({ page }) => {
    await page.goto('/login');
    await page.fill('[data-testid="auth-email-input"]', 'alice@buzzhive.com');
    await page.fill('[data-testid="auth-password-input"]', 'alice123');
    await page.click('[data-testid="auth-login-btn"]');
    await page.waitForURL('**/');

    const navSearch = page.locator('[data-testid="nav-search"]');
    await navSearch.click();
    await page.waitForLoadState('networkidle');

    expect(page.url()).toContain('/search');
    await expect(page.locator('[data-testid="nav-search-input"]')).toBeVisible({ timeout: 5000 });
    console.log('✅ Navigation to search works!');
  });
});
