apiVersion: 1
datasources:
  - name: Infinity
    uid: infinity
    type: yesoreyeram-infinity-datasource
    access: direct
    isDefault: true
    jsonData:
      allowed_hosts:
        - "http://localhost:3002"
        - "https://raw.githubusercontent.com"
